"""empty message

Revision ID: 3c3ccb763138
Revises: 
Create Date: 2020-04-21 16:23:52.626676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3ccb763138'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Core',
    sa.Column('xid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('subheading', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('Heartbeat_Receive',
    sa.Column('xid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('last_beat', sa.String(length=255), nullable=True),
    sa.Column('notify_afer', sa.Integer(), nullable=True),
    sa.Column('allow_notifications', sa.Boolean(), nullable=True),
    sa.Column('all_notifications', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('Heartbeat_Send',
    sa.Column('xid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('Notification',
    sa.Column('xid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('Request',
    sa.Column('xid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('expected_status', sa.Integer(), nullable=True),
    sa.Column('check_type', sa.String(length=255), nullable=False),
    sa.Column('check_method', sa.String(length=255), nullable=True),
    sa.Column('post_data', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('notify_afer', sa.Integer(), nullable=True),
    sa.Column('allow_notifications', sa.Boolean(), nullable=False),
    sa.Column('all_notifications', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('Request_Result',
    sa.Column('xid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('request_xid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_xid'], ['Request.xid'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('heartbeat_notification_table',
    sa.Column('heartbeat_xid', sa.Integer(), nullable=True),
    sa.Column('notification_xid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['heartbeat_xid'], ['Heartbeat_Receive.xid'], ),
    sa.ForeignKeyConstraint(['notification_xid'], ['Notification.xid'], )
    )
    op.create_table('request_notification_table',
    sa.Column('request_xid', sa.Integer(), nullable=True),
    sa.Column('notification_xid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_xid'], ['Notification.xid'], ),
    sa.ForeignKeyConstraint(['request_xid'], ['Request.xid'], )
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_notification_table')
    op.drop_table('heartbeat_notification_table')
    op.drop_table('Request_Result')
    op.drop_table('Request')
    op.drop_table('Notification')
    op.drop_table('Heartbeat_Send')
    op.drop_table('Heartbeat_Receive')
    op.drop_table('Core')
    # ### end Alembic commands ###
